### ISSUE TITLE
Assertion error when running

### ISSUE THREAD

**Issue by gcoombe** [elliottsj/jscodeshift-typescript-example#4]
Hi there,

Thanks for all your work on this, I've been following along closely since we'd really like to use jscodeshift on our ts codebase. When I run this example (and when I use the same approach on my codebase) I get the following error: 

```
AssertionError [ERR_ASSERTION]: false == true
    at new Patcher (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/patcher.js:20:10)
    at /Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/patcher.js:174:19
    at maybeReprint (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/printer.js:97:41)
    at print (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/printer.js:77:29)
    at exports.printComments (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/comments.js:324:22)
    at printWithComments (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/printer.js:63:16)
    at print (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/printer.js:68:20)
    at Printer.print (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/lib/printer.js:122:21)
    at Object.print (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/node_modules/recast/main.js:6:33)
    at Collection.toSource (/Users/gcoombe/zenefits/jscodeshift-typescript-example/node_modules/jscodeshift/src/Collection.js:179:21)
```

**Comment by gcoombe** [comment]
ahhh I originally installed with `yarn` which would have ignored the package lock, but when I installed with npm it worked. I therefore assume that it's some an issue caused by some variation of the versions.

Specifically pinning the jscodeshift version to 0.5.0 seemed to work

**Comment by elliottsj** [comment]
This should no longer be a problem with #5
